In [39]:
import numpy as np 

In [40]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [41]:
z=np.concatenate([x,y])
print(z)
print(x)
print(y)
print(z)
print(id(x))
print(id(y))
print(id(z))
print(10)
zz=np.concatenate([x,y,z,x])
print(zz)

[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
1431938998064
1431938625408
1431938557792
10
[1 2 3 4 5 6 1 2 3 4 5 6 1 2 3]


In [42]:
x=[[1,2,3,3],[5,5,6,7]]
x=np.array(x)
y=[[12],[2]]
y=np.array(y)

z=np.hstack([x,y])
print(z)

[[ 1  2  3  3 12]
 [ 5  5  6  7  2]]


In [43]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
# np.shape(x)
x.shape=(6,3)
print (x)
np.hsplit(x,[3,4,5,2,6])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


[array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]),
 array([], shape=(6, 0), dtype=int32),
 array([], shape=(6, 0), dtype=int32),
 array([], shape=(6, 0), dtype=int32),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]]),
 array([], shape=(6, 0), dtype=int32)]

In [44]:
#computational part of np array 
x=np.array([0,1,3,4,5])
y=np.empty(5)
print(id(y))
np.multiply(x,10,out=y)
print(id(y))

1431938223440
1431938223440


In [45]:
y=np.zeros(10)
np.power(2,x,out=y[::2])
print(y)

[ 1.  0.  2.  0.  8.  0. 16.  0. 32.  0.]


In [48]:
x=np.array([1,2,3,4,5])
print(x.sum())
print(np.sum(x))
print(np.add.accumulate(x))

15
15
[ 1  3  6 10 15]
